"""Extra columnto roads table

Revision ID: e91889b1d16a
Revises: 167bbe48cca0
Create Date: 2024-07-12 18:55:35.890471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91889b1d16a'
down_revision: Union[str, None] = '167bbe48cca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roads', sa.Column('end_location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'roads', 'locations', ['end_location_id'], ['location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roads', type_='foreignkey')
    op.drop_column('roads', 'end_location_id')
    # ### end Alembic commands ###
